 services:
  fluxer-discord-bridge:
    image: rillabel/fluxer-discord-bridge:latest
    working_dir: /Bot
    volumes:
        - [PATH TO THE FOLDER WITH BRIDGES.YAML]:/Bot/db
    environment:
        - FLUXER_TOKEN=[YOUR FLUXER TOKEN]
        - DISCORD_TOKEN=[YOUR DISCORD TOKEN]
        - CMD_PREFIX=brdg;
